export const P = {
  chat: "/api/v1/chat",
  conversations: "/api/v1/conversations",
  convMessages: "/api/v1/conversations/{conv_id}/messages",
  conversation: "/api/v1/conversations/{conv_id}",
  kb: "/api/v1/kb",
  kbDocs: "/api/v1/kb/{kb_id}/documents",
  docReprocess: "/api/v1/documents/{doc_id}/reprocess",
  docChunks: "/api/v1/documents/{doc_id}/chunks",
  models: "/api/v1/models",
  model: "/api/v1/models/{model_id}",
  usageSummary: "/api/v1/usage/summary",
  usageMe: "/api/v1/usage/me",
  usageUsers: "/api/v1/usage/users",
  authLogin: "/api/v1/auth/login",
  authLogout: "/api/v1/auth/logout",
  authMe: "/api/v1/auth/me",
  authChangePassword: "/api/v1/auth/change-password",
  users: "/api/v1/users",
  user: "/api/v1/users/{user_id}",
  userGrants: "/api/v1/users/{user_id}/grants",
  audit: "/api/v1/audit",
  branding: "/api/v1/branding",
  license: "/api/v1/license",
  settings: "/api/v1/settings",
  apiKeys: "/api/v1/api-keys",
  apiKey: "/api/v1/api-keys/{key_id}",
} as const;
